// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuO_CaNUj0e8TrZ3_dOrQOokn4YKSQbVc',
    appId: '1:859050604457:web:d90b5e0cf8cfa126e5b6b8',
    messagingSenderId: '859050604457',
    projectId: 'mayssaapp-99975',
    authDomain: 'mayssaapp-99975.firebaseapp.com',
    storageBucket: 'mayssaapp-99975.appspot.com',
    measurementId: 'G-Y58L2BD4B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGTXBIyAkteCJB1XsH5AYKe9XTzQDVITE',
    appId: '1:859050604457:android:d35f61ec37ba7d94e5b6b8',
    messagingSenderId: '859050604457',
    projectId: 'mayssaapp-99975',
    storageBucket: 'mayssaapp-99975.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW4tHsmUKfad-XadQxIkM-8Xz6aHMVPhM',
    appId: '1:859050604457:ios:5515c583186d2254e5b6b8',
    messagingSenderId: '859050604457',
    projectId: 'mayssaapp-99975',
    storageBucket: 'mayssaapp-99975.appspot.com',
    iosBundleId: 'com.example.mayssaApp',
  );
}
